Gemfile.lock
sass/screen.scss

This temporarily fixes the pagination on mobile so it does not look broken. We may consider reorganizing the stylesheets a bit and removing some `!important`s there.

@anyone Fix pagination on mobile.

---

plugins/expanded_image.rb
source/_includes/article.html

Allows you to make images that break out of the main column, then brings them back. Similar to the CocoaPods blog. Though without the BG colour change.

@alloy => Support expanded images in blog posts

---

source/_posts/2015-08-06-open-sourcing-energy.markdown

@orta fun mini tweak
www.objc.io is missing its http://
Doesn't like https:// either, so not that
And there ends my Friday :)

Link fix: add http:// for objc.io in "open-sourcing-energy"

---

_posts/2015-08-19-Cocoa-Architecture:-Switchboard-Pattern.markdown

@alloy feedback and thoughts around this is welcome too. 
Things I've wondered about talking about:
* Eigen's problems with async view controllers, and the idea of making it just return view controllers, then having a separate object for the push to nav etc bit
* More on Eidolon?
* Perhaps digging a bit further into the embedded JLRoutes object in Eigen/Energy
Can you two think of other expansions within this? Also needs a finishing up section.

@ashfurrow => Initial stab of the Architecture: ARSwitchboard post

---

Gemfile.lock

Version 0.16.1 [has been yanked](https://rubygems.org/gems/celluloid/versions/0.16.1). [No one really knows why](https://github.com/celluloid/celluloid/issues/612).

@orta => Updates celluiloid.

---

_includes/category_feed.xml

Fixed the layout warnings [with this advice](https://github.com/jekyll/jekyll/issues/2712#issuecomment-51614932).
Tested locally by running
```sh
PRODUCTION="YES" bundle exec jekyll build -d _gh-pages
```
without warnings.

@orta: Specifies no layout for category feeds.

---

.travis.yml
Rakefile
_config.yml

Let me know if I've violated Rakefile etiquette. Additionally, people may still submit PRs from forks, since the `$GH_TOKEN` is only needed to deploy, which PRs don't trigger. 
I should note that this _should_ work on master, but we won't know for sure until we merge. 
Fixes #136.

@orta: Automatically deploy site upon push to master

---

_config.yml
_includes/head.html

* Our canonical URLs were pointed to artsy.net - https://twitter.com/subdigital/status/641597152431505408
* There was no auto-discovery for RSS - https://twitter.com/subdigital/status/641356648678690817

@joey => Fixes to HEAD metadata

---

_posts/2012-10-09-how-to-run-rspec-test-suites-in-parallel-with-jenkins-ci-build-flow.markdown
_posts/2015-09-24-splitting-up-a-large-test-suite.markdown

As requested in https://github.com/artsy/gravity/pull/9251, this adds a post describing the `sliced` approach for splitting up our large rspec test suite for Jenkins' build flow plug-in. I also mentioned it on the old post.
It's a small idea... not sure it's worth a post on its own.

@anyone: New post: Splitting up a large test suite

---

_posts/2014-11-13-eidolon-retrospective.markdown
_sass/screen.scss

Particularly, unordered lists and previous/next article links on mobile. 
----------------
Before:
After:
----------------
Before:
After:

@orta: Style fixes

---

_sass/screen.scss

The `border-bottom` trick to underline links looks bad when links wrap:
Links wrap a lot, especially given the narrow content area. The default behavior looks slightly less bad:
...but still looks bad. I made the easy change, but I'd rather fix the underline thickness. Is that possible?

@craigspaeth: Link underlines should be compatible with newlines

---

_sass/screen.scss

Lowered the z-index of the logo-container so now any links underneath it are clickable.

Fix for #172 - Links in the footer are not clickable

---

_sass/screen.scss

Now when the stuck class is added to header#banner, the top property is animated via css.

Fix for #94 - Sticky header jump

---

_posts/2016-01-30-iOS-Junior-Interviews.markdown

I was reading this fantastic article (thank you for sharing it) and noticed a few typos.
'ice-brakers' -> 'icebreakers'
'More infö' -> 'More info'
Thanks!

Fix typos in 2016-01-30-iOS-Junior-Interviews

---

_posts/2016-06-24-typealias-for-great-good.markdown

@ashfurrow Great post!
The code snippet is not consistent with the paragraph above.

Fix code snippet

---

_sass/screen.scss

So there were two issues: first, we were using a min-width of 600px instead of 800px (that was the only instance we were using 600, figured it was a typo) and also we need to make the clodeblocks full-width on small screens to prevent this:
Fixes #239.

Fixes iPad layout issue in codeblocks

---

_layouts/default.html
_sass/screen.scss

switch out low-res brand logo img for razor sharp svg logo (the svg logo was sourced from the icon font on artsy.net)
before:
after:

feat(logo): change logo to svg

---

_layouts/default.html
_sass/screen.scss

addresses: https://github.com/artsy/artsy.github.io/issues/130
- fix broken logo click (no regression on footer link issue)
- refactor common style widths into a single mixin `desktop-container`
- refactor logo html to support simplified styles

fix(logo): expose logo click

---

_layouts/search.html
_sass/screen.scss

addresses: https://github.com/artsy/artsy.github.io/issues/92
add simple spinner (based on style guide) on search page that gets
removed when google loads their results
note: the spinner gets removed slightly before the results render on the
page so the user experience is a little rough

feat(search): add spinner

---

_includes/_series_bio/open-source-by-default.md
_includes/_series_bio/react-native-at-artsy.md
_includes/article.html
_layouts/series_index.html
_plugins/series_index.rb

Had a train ride, choo choo. 
Posts now will link to their series, and a series index can now contain a header bio in markdown
e.g.

Add support for having a markdown bio above a series

---

_sass/screen.scss

When you're linking to a specific hash, it'd be useful that the link would transport you to the exact location of that location.
Because there's static header of `221px`, the offset here is `121px`. I'm not exactly sure how to calculate that, but some trial and error put me on this exact value. Note that when the header isn't collapsed this won't be right, but then you'd be linked to the top of the page, since it would be visible already.
for example in [Emission](https://github.com/artsy/emission) you link to the [JS Glossary]http://artsy.github.io/blog/2016/11/14/JS-Glossary() like `http://artsy.github.io/blog/2016/11/14/JS-Glossary/#yarn`.

add an offset to anchor links

---

.vscode/settings.json
Dangerfile
Gemfile.lock
_config.yml
_posts/2017-01-04-OSS-FAQ.md
_sass/screen.scss

OSS FAQ for Engineers

---

_posts/2017-02-05-Retrospective-Swift-at-Artsy.md

You probably want “Apple TV” or “tvOS”. 📺 
PS: thanks for this great article!

Fix naming (minor)

---

_sass/screen.scss

This is certainly open for debate, but when clicking through to the [longform article](http://artsy.github.io/blog/2017/02/05/Front-end-JavaScript-at-Artsy-2017/) off of Jest's website today it immediately struck me that the reading width is far wider than what the eyes are naturally comfortable with. 
Going over to Medium (where I assume they've done an enormous amount of user testing) I see that they've capped their width at 700px, and so I've brought this PR in line with that. 
This also reduces some of the cramp between the Artsy logo and the left-hand content margin.
**Before:** 
**After:**
Thoughts?

Reduce longform article width

---

_posts/2017-03-05-artsy-technology-stack-2017.md

A few edits to this paragraph:
- "Provisioning" --> "Operations"
- A first sentence on Terraform and the effects of its adoption
- "We started developing..." as Hokusai is still yet to be a v1 release
- "...in order to manage a containerised workflow, CI and deployment to Kubernetes" as Hokusai aims to cover the whole shebang - dev / test / CI / artifacts and deployment

Provisioning --> Operations

---

_includes/gh_comments.html
_layouts/epic.html
_posts/2017-07-06-React-Native-for-iOS-devs.markdown
_sass/epic.scss
images/epic/comment-header.svg

Allows adding comments to posts - fixes #300 
This only applies to epic-styled posts. In order to do it, you need to create an issue like #362 then provide that inside the YAML front-matter.
Our implementation uses https://github.com/orta/gh-commentify behind the scenes to ensure we don't get rate-limited by GitHub. It uses a token from an account with no access to anything.

Add GitHub issues as comments for posts

---

_sass/screen.scss

Couldn't find an specific issue for that but there was a element selector missing for small screens media query that made it very hard to navigate through the archived (and authors) posts list when using a mobile browser.
| Before | After |
|---|---|
| <img width="487" alt="screenshot 2017-08-27 11 18 02" src="https://user-images.githubusercontent.com/700480/29750642-ea0f060e-8b19-11e7-82f1-8ee2c9164eb2.png"> | <img width="487" alt="screenshot 2017-08-27 11 18 19" src="https://user-images.githubusercontent.com/700480/29750644-eec25a84-8b19-11e7-8807-67b5e5865ba7.png"> |
I still have some concerns on how `#id`s are being used on CSS and some elements like the post list in different pages today have duplicated styles, but that would require a larger change and styles refactoring than I can …

Bugfix - Missing CSS media query style for blog archives list

---

README.md
_sass/epic.scss

**Before:** 
**After:**
Thinking... Looking around the blog code things are definitely showing their age. Would love to try an experimental migration over to [Gatsby](https://www.gatsbyjs.org/) at some point just to see what kind of effort it would take given existing content.

@orta => Adjust mobile layout padding

---

_posts/2017-07-06-React-Native-for-iOS-devs.markdown

For some reason Markdown wasn't picking this up as a link, I'm hoping using an explicit anchor tag will.

Fix broken link to comments

---

_posts/2017-11-27-Babel-7-and-TypeScript.markdown

Covers recent learnings around Babel 7 + TypeScript, plus a quick-start [example project](https://github.com/damassi/babel-7-typescript-example)

Add Babel 7 + TypeScript post

---

_posts/2017-09-05-Modernizing-Force.markdown
_posts/2017-11-29-Express-Reloadable-Update.markdown

Covers a few issues discovered while working with the publishing team as well as subsequent updates to `@artsy/express-reloadable`.

[Post] Express Reloadable: Optimizing Express.js Development Speed

---

_layouts/author_index.html

Fixes #411. I tested `rake build` (these pages aren't served normally) before and after the change and it worked 👍

Changes comparison for author pages

---

_posts/2018-03-19-making-a-components-pod.markdown

same as what has been done for Emission. 
Same disclaimer; it could be that `root` has to be prepended, which was the case in my implementation.

use ruby api to retrieve spec details

---

_layouts/author_index.html

I noticed [my author page](http://artsy.github.io/author/ash/) wasn't including any posts where the `author` frontmatter was an array. This should fix it.

Fixes author pages with multiple-author posts

---

_posts/2018-07-25-Relay-Networking-Deep-Dive.markdown

This turns a few raw URLs in the (excellent!) Relay guest post into proper hyperlinks.

Turns URLs into hyperlinks.

---

_posts/2018-08-24-How-to-debug-jest-tests.markdown

I mentioned in Slack that I was using making good use of this post, and furthermore that I was doing so with Jest's `--watch` mode. 
Just wanted to document that option here. 
Not sure how my addition affects the flow of your narrative — happy to adjust if you'd like!

Document using Chrome debugger with Jest's watch mode

---

Rakefile

Our `Rakefile` stars the Jekyll server using `sh`, but when we hit ctrl-c to stop the server, `rake` interprets that interrupt as an error and produces a big stack trace:
This PR puts the Jekyll server in its own process and traps the ctrl-c interrupt to `kill -9` that process:

Make quitting the server less noisy

---

_posts/2018-11-19-mjml.markdown

It currently links to `http://artsy.github.io/blog/2018/11/19/mjml/mjml.io` when generated

Fix url to mjml.io

---

_posts/2019-01-28-from-tslint-to-eslint.md

Adds a post on migrating from TSLint to ESLint + a use-case example around linting GraphQL code.

Add "From TSLint to ESLint" post

---

_posts/2019-01-28-from-tslint-to-eslint.md

Fixes one more typo -- an unnecessary codeblock at the bottom of the post:

Remove erronious codeblock at bottom of post

---

_config.yml
_posts/2018-11-19-mjml.markdown
_posts/2019-01-23-artsy-engineering-hiring.md

Currently, clicking on my name or @mdole's name next to an article takes you to a nonexistent page. 
This is because we put `_` in our author keys. When the author pages are generated, [`_` are replaced with `-`](https://github.com/artsy/artsy.github.io/blob/2a3217947df034c3f29db153441a49b5c3c18997/_plugins/author_generator.rb#L59) - but all the links to the author pages take the key verbatim. 
This PR includes the simplest way to fix this - replacing any author keys that use underscores to use hyphens instead. Right now that's me & @mdole.
This could be more permanently fixed by changing all the references to `author/{{key}}` to also replace `_` with `-`. [It appears there is even a filter to do this already](https://github.com/artsy/artsy.github.io/blob/2a3217947df034c3f29db153441a49b5c3 …

Change underscores in author keys to hyphens, so that author links work

---

_includes/article.html
_layouts/epic.html
_sass/epic.scss

Beyond being a good general guideline, on blog posts that deal with fast-changing technologies (like ours), it's _especially_ important to include the date of the post near the title of the post. This was [brought up on Slack](https://artsy.slack.com/archives/C02BGC5PW/p1557947974081900?thread_ts=1557947912.081800&cid=C02BGC5PW) and I wanted to tackle this now.
Here's what this looks like on classic posts:
And here's what it looks like on the modern, "epic" layout:
(I went with the same grey here that we use for datestamps on comments.)
I'm open to design feedback on this 👍 
Fixes #544.

Adds date to blog posts under the title

---

_posts/2019-05-24-server-rendering-responsively.md

The "use" in context seemed a bit confusing, like we were telling the reader to use something. Would work with a question mark but that read a bit strange with the main section header

Remove confusing "use"

---

Dangerfile
LICENSE
README.md
_config.yml
_posts/LICENSE

Fixes https://github.com/artsy/README/issues/232
This PR adds the MIT and CC-4.0-BY licensing. I decided to go with `LICENSE` and `_posts/LICENSE` (instead of Orta's suggestion of `LICENSE` and `LICENSE-CODE`) because it plays nicer with GitHub's user interface for "view license". I also excluded the two new files from Jekyll builds. Finally, Prettier cleaned up the readme a bit.

Adds MIT/CC-4.0-BY co-licensing

---

.travis.yml

This is to workaround a bug on CI, detailed in this blog post: https://bundler.io/blog/2019/05/14/solutions-for-cant-find-gem-bundler-with-executable-bundle.html Here's an example of the failing build: https://travis-ci.org/artsy/artsy.github.io/builds/583730734
Since deploys are done from Travis, we'll be blocked on new posts until we get this fixed.

Updates Ruby version

---

_posts/2020-02-20-deploying-canaries-with-auto.markdown

I recently enabled automatic canary package releases across all our auto powered repositories. This blog post details some of the motivations behind that. 
Feedback welcome 🙏. It's a little high level right now, let me know if I should dig into more specifics. 
cc @mzikherman, @eessex, and @anandaroop being as you've all been apart of this process in some way.

Add blogpost on using auto to deploy canary packages

---

.travis.yml

@pepopowitz noticed that in #622 I missed the `` teaser tag. We have a Danger rule for this specific problem, but Danger failed to catch the problem in the PR. It failed because the `DANGER_GITHUB_API_TOKEN` environment variable was no longer valid, so the invocation failed. Normally, Danger would fail the build, but it didn't because of how we structured the CI config. Let me explain.
We skip the Danger requirement for pull requests from external contributors because they don't have access to the environment variable on their builds. But how our script innovation worked had us ignoring the Danger failure. Reversing the order should fix this.
I have also updated the Travis config with a valid GitHub personal access token.

Fixes Danger invocation

---

open-source/index.html

Switching iteration order of `ruby` and` devops` categories so they render in order of navigation links.
Sorry my mental model not matching the scrollto functionality was killing me :)

Correct open-source category rendering order

---

_config.yml
_includes/head.html

⚠️ I had trouble installing dependencies so I wasn't able to _actually_ test these changes locally 😬 
The `href` inside the head for is empty because `subscribe_rss` isn't defined but being used in `_includes/head.html`
```html
<link href="" rel="alternate" title="Artsy Engineering" type="application/atom+xml">
```
Define `subscribe_rss` and and update `_includes/head.html` to use `root_url`

Set href in link for RSS auto discovery.

---

Gemfile.lock

After the rabbit hole of issues we faced yesterday, @pepopowitz, I decided to zoom back and think about why this might be happening. I figured that the Bundler version in the `Gemfile.lock` being so behind might be the issue, but I still ran into some problems with dependencies that needed native extensions (the compiler errors we were seeing yesterday).
So I updated the Bundler version and a select few dependencies that were failing, basically adding another one until the command succeeded. 
```sh
bundle update --bundler ffi rdiscount compass
```
I then ran `bundle pristine` to make sure things were actually installed as they would be on others' computers, cleaned the build directory, built the site, and served it locally:
```sh
bundle pristine
rm -rf _gh-pages
bundle exec rake build …
```

chore: update dependencies to fix macos bundler problems

---

_config.yml

Updates the site URL in config.yml to specify `https` instead of `http`. 
I submitted the podcast.xml to Google [via PubSubHubbub](https://support.google.com/podcast-publishers/answer/9890138?hl=en) a week or two ago, and Artsy Engineering Radio is still not listed there. I suppose it's possible they're just not approving things over the holiday break, but [troubleshooting docs](https://support.google.com/podcast-publishers/answer/9482890?hl=en) suggest to verify that the RSS feed is valid. 
I ran it through a validity checker again and there are no errors, but there is a single warning: 
It took me a few reads to figure out it was pointing out that the RSS feed is at `https` but in the xml we say it's at `http`. 
That would also align with another item in the troubleshooting docs: "Do …

chore/fix: Specify https for the site URL

---

_posts/2021-01-06-introducing-artsy-engineering-radio.markdown

The longer markdown links were getting split into two lines when the source was auto-formatted, which resulted in them not working. 
This inlines line the longer links.

fix: inline long markdown links

---

Rakefile
_config.yml
podcast.xml

This PR adds the ability to specify links for a specific episode in the config. It also adds notes to episode 2. 
The links get attached to the `content:encoded` element of the item in podcast.xml as formatted html that looks like this: 
That element gets rendered in the podcast player, usually as the details that show up when an episode is playing.

feat: add show links to feed

---

.github/workflows/stale.yml

@dblandin and I were doing some grooming of requested-post issues and noticed we have some old ones. We thought it might be good to keep this issue list relatively clean.
Introduces the [stale](https://github.com/actions/stale) action to mark stale/close inactive requested post issues.
Currently set up with `debug-only:true` and a very-frequent cron to test it out.

feat: Testing a github action to mark/close stale requested posts

---

.github/workflows/stale.yml

The action added in #655 ran, but it didn't reach completion due to hitting a limit on number of operations.
This ups the limit so we can see it reach completion before turning off debug mode.

feat: bump up max number of operations for stale requested posts action

---

.github/workflows/stale.yml

Given #659 will be open for a few days, this PR updates the stale requested-posts action to run once a day instead of every ten minutes, to avoid hitting the GitHub API unnecessarily. 
Once this PR is merged, I'll remove the scheduling update from #658.

feat: throttle down the stale requested-posts action

---

_includes/head.html

@pepopowitz and I added the capability to handle a canonical URL field from posts. If `canonical` is included in the post, it will be added to the page. Otherwise, the canonical URL will be generated as before.

feat: Add ability to include canonical url field from posts

---

_sass/epic.scss

Overrided padding on last line of blockquote to 0px.
Before:
After:

fix: Remove padding on last line of blockquote

---

.github/workflows/stale.yml

The action to mark/close stale requested-post issues [did what we wanted it to](https://github.com/artsy/artsy.github.io/actions/runs/549179456), so this PR turns off debug-only for the action.

feat: enable stale requested-post action

---

googlef51b779dd18cf8a4.html

This is required so that we can claim the domain in Google Search Console.

Add google verification file

---

podcast.xml

Last week's episode didn't show up in google podcasts, and it looks like it's because the feed isn't valid:
The error is coming from unescaped ampersands: 
This escapes both places we emit the `description`.

fix: escape descriptions in podcast feed

---

_posts/2012-01-31-delaying-carrierwave-image-processing.markdown
_posts/2012-06-25-replacing-hashbang-routes-with-pushstate.markdown
_posts/2014-04-02-refactoring-infrastructure.markdown
_posts/2015-11-12-Using-OCR-To-Fix-A-Hilarious-Bug.markdown
_posts/2017-06-30-danger-one-oh-again.md
_posts/2018-02-06-apogee-technical-retrospective.markdown
_posts/2018-06-18-On-Obsessive-Statelessness.markdown
_posts/2018-12-11-GraphQL-Stitching.markdown

feat: adopt inclusive language within published blog posts

---

_posts/2012-05-27-using-jenkins-for-ruby-and-ruby-on-rails-teams.markdown
_posts/2012-07-10-on-demand-jenkins-slaves-with-amazon-ec2.markdown
_posts/2012-10-10-artsy-technology-stack.markdown

We have **a lot** of cases of [`master` in blog posts](https://github.com/artsy/artsy.github.io/search?q=master). Most of them are links to repos, many discuss the `master` branch in text, and then there were a few usages in regards to master-slave replication. 
This PR updates those more egregious master-slave usages according to the product's replacement for that language: [Jenkins now uses controller-agent](https://www.jenkins.io/doc/book/using/using-agents/) and [Solr now uses leader-follower](https://solr.apache.org/guide/8_11/index-replication.html). 
Each updated article includes a footer indicating the original content has been updated for inclusive language. Example: 
---
I'd love to hear opinions on what we should do about the remaining usages of `master`.

chore: adopt inclusive language - egregious cases of master

---

_config.yml
_drafts/artsy-engineering-culture-2017.md
_posts/2017-04-14-artsy-technology-stack-2017.md
_posts/2022-01-06-a-year-in-review-2021.markdown

The Artsy Engineering author link 404s because the link points to `/author/artsy_engineering` and the author page is generated with a slug of `/author/artsy-engineering`. This takes the seemingly easier approach of updating the author key in the `_config` file rather than changing how links or pages are generated.

chore: update year in review authors

---

_plugins/categories.rb

Tiny follow up to fix search results that include results like:
```
Category: #<struct Jekyll::CategoryPageGenerator::Category name="webpack", count=1, dir="webpack">
```

Fix search indexing of new category pages

---

.prettierrc
.vscode/settings.json
_posts/2022-08-23-getting-around-7-day-cookie.markdown

Adds a new post describing how we solved the issue of Safari wiping cookies after 7 days, leading to the consent banner constantly reappearing for users and breaking our UX. 
Proof-readers welcome 🙏 
cc @artsy/grow-devs

Add post on working around Safari's 7-day cookie limit (ITP) 

---

css/epic.scss
javascripts/related-articles.js

Tiny layout fix when the `related-articles` aside is empty. 
(Necessary, since not all posts will have related posts)
Before and after…

fix: layout when related articles section is empty

---

_includes/head.html
_sass/base/_typography.scss
_sass/custom/_fonts.scss
_sass/partials/_blog.scss
artsy-x-react-native.html
css/epic.scss
css/screen.scss

We recently canceled the subscription that was supplying our Garamond fonts, leading to the blog having Times New Roman and a little "view all fonts" thingy in the corner:
Took the opportunity to move to our preferred fonts and do light resizing to bring them in line with Palette:
Definitely lots more cleanup that could be done here, but seemed like a reasonable start.

feat: update to sans-serif fonts

---

_layouts/epic.html

Updates our OSS links in the blog to our Github org, filtered by 'sources'. This is way more accurate, comprehensive and up to date. I think anybody stumbling upon this list would be very, very psyched. I know I just was, paging through. Happy to revert this if there are any strong complaints. The old blog pages capture just a small piece of things.

chore: Update OSS links to something more up to date
