source/_posts/2015-01-21-cocoapods-keys-and-CI.markdown

Someone asked on twitter, was a bit too long for 140 chars.

@ashfurrow => cocoapods keys + CI post

---

source/_posts/2015-04-03-artsy-engineering-compensation-framework.markdown

Currently in draft, with some early reviews done offline.

Artsy Engineering Compensation Framework.

---

source/_posts/2015-03-26-creating-a-dynamic-single-page-app-for-our-genome-team-using-react.markdown

Feel free to suggest a more interesting title. :D Any comments welcome!

@orta @joeyAghion React post

---

Gemfile.lock
source/open-source/repositories.json
source/open-source/repositories_view.js

Pretty minor things. 
Mainly I wanted to make sure Moya was linked to.

@orta => Several Fixes for OSS Page

---

source/_posts/2014-09-24-using-pattern-recognition-to-automatically-crop-framed-art.markdown

@gristleism => Fix broken link to OpenCV docs

---

sass/screen.scss

@damon => Fixes

---

Gemfile.lock
_posts/2015-08-24-Cocoa-Architecture:-Hybrid-Apps.markdown

+ @alloy 
Things I've debated, and am open to adding
- Talking about the difficulties in keeping issues active/up to date between projects
- Keeping on top of routes
- Changes the sites have to do for Eigen

@ashfurrow => Architecture: Hybrid Apps

---

_config.yml

Missed the setting for the dir

@ashfurrow => Brings back the category pages- fixes #138

---

.travis.yml
Rakefile

@orta: Fixes auto deploys.

---

README.md

To reflect our fancy new automatic deploys.

@orta: Updates deploy instructions

---

_posts/2015-08-27-swift-trek-2-the-wrath-of-count.markdown

First draft. 
Fixes https://github.com/artsy/mobile/issues/52

@orta: Swift 2 migration article

---

README.md
_posts/2015-09-04-releasecop-tracks-stale-releases.markdown
_sass/screen.scss

I had posted about the [releasecop](https://github.com/joeyAghion/releasecop) gem on my personal blog, but never here. (But mostly, I just want to break the iOS streak.)
I made a few other updates that I don't think are controversial, but any feedback is welcome.

@orta: new post about releasecop

---

.travis.yml
Rakefile

I tried what I could locally, but will be watching this build closely to confirm.

@ashfurrow: Perform github set-up only if deploying from a source build (fixes #153)

---

_includes/article.html
_includes/post/mini-author.html

@ashfurrow => Show author names next to indexes of posts

---

_includes/header.html

@owendodd => fix headers

---

_plugins/youtube.rb
_posts/2015-11-05-Emergence-Code-Review.markdown

The video is still in processing, so don't merge this until this link: https://www.youtube.com/watch?v=NErVWhEzIBM actually works.
I added a quick plugin that breaks the youtube video out of it's single column for the inline version of the video too.

@alloy => Add Emergence Code Review post

---

_posts/2015-09-24-mvvm-in-swift.markdown

...but what mechanism to we use to do this...
changed to
...but what mechanism do we use to do this...

to > do - minor correction

---

_posts/2015-12-08-reactive-cocoa-to-rxswift.markdown

@orta: Adds RxSwift post

---

_config.yml
_posts/2015-12-09-docker-for-development.markdown

I would love comments from people who haven't used docker much yet! cc @ashfurrow @craigspaeth @sweir27

@dylanfareed: docker for development

---

_posts/2015-09-30-Work-Offline-More.markdown

Merges in #174

---

_posts/2015-12-11-License-and-You.markdown

Had to wait for my computer to update to 11.2 - it's taking a while.
@alloy would love a one over too

@ashfurrow => Added a blog post about licensing

---

_config.yml

Added [representable-expandable](https://github.com/ashkan18/representable-expandable) to the list of our open source projects.

@anyone => Added representable-expandable to list of our open source projects

---

_config.yml

fixed order, just notcied everything is in created date order, added representable-expandable to the end of the list

@ashkan18 => Fixed order

---

_posts/2015-12-15-Automating-Testflight-Deploys.markdown

Small improvements

---

_posts/2015-12-21_future_fridays.markdown

/cc @alexanderfabry @mzikherman @ashkan18 @dblock @wrgoldstein @bhoggard @sweir27

New post: Future Fridays

---

_posts/2016-01-14-eidolon-code-review.markdown

Eidolon walkthrough.

---

_posts/2016-02-12-Code-Review-Energy-Sync.markdown

A simple post covering the sync video

Add sync post

---

_posts/2016-03-05-iOS-Code-Injection.markdown

I made a video, so I :ship:'d a blog post for it.

Add a blog post about injection

---

_config.yml
_posts/2016-03-09-public-speaking-part1-is-it-for-me.markdown

First in a 3 part series (I think). 
Issue around this post here: https://github.com/artsy/mobile/issues/76
Would like to 🚢 so let me know what y'all think!

[New Post] Public speaking - is it for me

---

_posts/2016-03-14-public-speaking-part2-where-to-start.markdown

First full draft. Happy with it, but equally would be keen on a read over from you all. 
Cheeeers!
cc/ @ashfurrow and @orta

Part 2 in public speaking series

---

_posts/2016-03-14-public-speaking-part2-where-to-start.markdown

Great article :+1:. I fixed a small typo. Looking forward to reading part 3 as well.

Fixed typo

---

_posts/2016-05-03-podspec-checksums.markdown

Re: https://github.com/artsy/eigen/pull/1464
@alloy does this feel right to you?

Added a post about podspec checksums with CP

---

_sass/screen.scss

Fix inline code when inside a <li>

---

Dangerfile
Gemfile
Gemfile.lock

Update danger to use proselint plugin

---

Dangerfile
_posts/helllow.markdown

Initial stab at adding a spellchecker.

[WIP] Spellcheck

---

_posts/2016-06-27-dependency-injection-in-swift.markdown

More thoughts from the eigen work on live.

DI in Swift

---

_posts/2016-07-03-handling-big-projects.markdown

"... development **]** where things"

Fixes typo

---

Dangerfile
Gemfile
Gemfile.lock
_posts/2016-07-03-handling-big-projects.markdown

More interested that changes in `danger-prose` works out.

Migrate our spell checker into a plugin, feedback from danger on the "big OSS" blog post

---

README.md
_posts/2016-08-09-Dev-Interview-Craig-Spaeth.markdown

For: https://youtu.be/-0WK1Ebis3M
Will release tomorrow

Initial video of dev interview series

---

_config.yml
_posts/2016-08-09-the-tech-behind-live-auction-integration.markdown

Gives you a name, and makes the front page only have the first paragraph 👍

@acjay => Adds alan to the blog config + a view more link

---

_includes/disqus.html
_includes/head.html

Use HTTPS scripts for external JS

---

_sass/screen.scss

tweak sticky header behavior to make the experience more like the sticky
elements on the artsy.net and more familar to general iOS/android app behaviors

feat(header): smooth sticky header

---

.travis.yml

Only run danger when the env var exists

---

.travis.yml
javascripts/gradient-fade.js

I think when I moved us to Jekyll, I lost this lovely bit of JS. Now it's back 👍

Makes sure that when you bounce, the BG is the colour you expect fixes #265

---

_layouts/series_index.html
_plugins/series_index.rb
_posts/2016-08-15-vscode.markdown
_sass/screen.scss

Improve series page on mobile / desktop

---

_posts/2016-08-31-Keyboard-Shortcuts-workshop.markdown

Just a quickie for a workshop I ran yesterday.

Add a keyboard workshop post

---

_posts/2016-08-30-swift-at-artsy-beginners-lesson-three.markdown

Lesson three for beginners

---

_posts/2016-09-06-Milestone-on-OSS-by-Default.markdown

@orta => Fix: spelling.

---

.gitignore
_posts/2015-04-03-artsy-engineering-compensation-framework.markdown
_posts/2016-01-30-iOS-Junior-Interviews.markdown
_posts/2016-10-10-Help!-I'm-becoming-Post-Junior.md

It's late, but this post just kinda kept on giving and ended being one iteration - a rarity for something this long with me.
I've been [using Ulysses](http://ulyssesapp.com) which is beautiful, and cleans up the markdown of things I've touched - so it's cleaned up the markdown on two other posts that I decided were part of a series. Which is why this diff is bigger than it would be normally. So you have to scroll to get to the actual article.
---
Main focus: You're hitting a point where you're comfortable as a programmer after your first year or two, but aren't sure how to grow from there. This should give you a lot of ideas to explore from.
Would love feedback from the peeps at Artsy who are either at this stage or are on the other side, especially
@sarahscott @kanaabe @xtina-starr …

Migrating past being a junior

---

_posts/2016-10-10-Help!-I'm-becoming-Post-Junior.md

Add a missing space [ci skip]

---

_posts/2016-06-19-graphql-for-mobile.markdown

heirarchical -> hierarchical
heirarchy -> hierarchy

Fixed typos

---

_posts/2016-09-16-Dev-Interview-Maxim-Cramer.markdown
_posts/2016-10-10-Help!-I'm-becoming-Post-Junior.md

Adds the video for Maxim, and moves the post-junior post to actually be the right date internally - can't change it in the URL alas, would break links.

Dev Interviews: Maxim

---

.bundle/config
_posts/2016-09-22-professional-development-at-artsy-engineering.markdown

I'm sure I'm missing something!

first draft of professional development

---

_posts/2016-10-08-eidolon-deploy-process.markdown

Fixes https://github.com/artsy/mobile/issues/36

Eidolon Deploy Process

---

_posts/2016-10-26-jwt-artsy-journey.md

* Made a few wording changes
* Removed extra lines between list items

@ashkan18: A few grammar fixes and style tweaks

---

_config.yml

* Adds our new search library, [artsy/stella](https://github.com/artsy/stella), to the open source projects list.

@ashkan18 : add stella to the open source projects list

---

_config.yml

Artsy 2013 & 2014 have same description.

correct project year typo

---

_layouts/post_longform.html
_posts/2017-02-05-Front-end-JavaScript-at-Artsy-2017.md
_posts/2017-02-05-Retrospective-Swift-at-Artsy.md
_sass/screen.scss

Adds a potentially wider, with larger text layout for long posts. Feels more medium-y.

Longform wide posts

---

_posts/2017-02-05-Retrospective-Swift-at-Artsy.md

as you **arer** building -> as you are building
The only **this** we miss is visual snapshots -> The only thing we miss is visual snapshots

Fixes typos in Retrospective-Swift-at-Artsy

---

_posts/2017-02-05-Retrospective-Swift-at-Artsy.md

Just a few minor edits - take 'em or leave 'em! ❤️

Swift edits

---

_posts/2017-02-06-React-Native-Workshop.md

Cleaned up the workshop notes, shipped a youtube video. Should be good to go 👍

Adds the React Native workshop code + video

---

_posts/2017-02-05-Front-end-JavaScript-at-Artsy-2017.md

Super minor, but there you go!

Edits for 2017 front end post

---

_posts/2016-11-24-bringing-artsy-to-amazon-echo-alexa.markdown

Add a paragraph describing when we need to go through certification process and how Lambda versioning and Alias can help in production/staging deployments.

Update lamda deployment and versioning information

---

_config.yml

Adding Elderfield, APRB and Artsy-EventService to list of opensource projects.

Add Elderfield, APRB and Artsy-EventService

---

_posts/2017-02-01-year-in-art.markdown

Some minor edits

---

_posts/2017-03-05-artsy-technology-stack-2017.md

I took your PR as an invitation to expand on the platform-related sections directly. Feel free to merge _or_ borrow from this into your own post _or_ ignore completely.

@orta: Offer some additions/modifications about Artsy's platform in 2017

---

_posts/2017-03-05-artsy-technology-stack-2017.md

Data pipeline addition to https://github.com/artsy/artsy.github.io/pull/326, let me know if this is too terse.

add data pipeline and analytics sections

---

_posts/2017-03-05-artsy-technology-stack-2017.md

I went top-to-bottom and iterated on everything inserting some big TODOs. I think these should be assigned to people for editing.

Major revisions across the board.

---

_posts/2017-04-02-generating-sitemaps-with-apache-spark.markdown

It would take too much work to open-source this part of cinder, so I'd rather not. Would love some comments from @joeyAghion @cavvia @izakp, etc.

@cavia => Generating sitemaps with Apache Spark.

---

_posts/2017-04-05-what-is-fastlane-match.markdown

/cc @KrauseFx (does this feel correct to you? )

Adds a post on match

---

_config.yml
_posts/2017-04-26-Relay-Mutations.md

Based on [this post](https://github.com/nikolasburk/magic-relay-mutations/blob/master/relay-mutations.md) from @nikolasburk
@dblock can you check that this makes sense to you as a non-GraphQL-native person?
@mzikherman does this feel good from the perspective of someone who has done it?
Only blocker from me is that Relay 1.0 was released, so the closing paragraph probably needs an update, but everything else feels lovely - thanks for arranging this Nik!

Adds a relay mutations guest post

---

_posts/2016-09-22-professional-development-at-artsy-engineering.markdown

From @acjay - fixes to links in professional references

---

_posts/2017-05-30-database-encryption.markdown

Post about how we encrypted our database without downtime.

Database encryption

---

_posts/2017-05-30-database-encryption.markdown

Just a couple very minor edits. ❤️

Minor edits

---

_posts/2017-07-06-React-Native-for-iOS-devs.markdown

ot -> got
it's -> its
hypotherical -> hypothetical
this questiona useful hypothetical... -> this question a useful hypothetical...

Fix a couple small typos

---

.travis.yml

Set CI vars via the site - fixes #356

---

_posts/2017-07-23-api-open-non-commercial.md

A nice quick announcement - wanted to also include a general TLDR for the API, as I could imagine it might be the first time a few popped have heard of it.
Any ideas what else you'd want in there?

Initial post announcing changes in TOS for artsy API

---

_posts/2017-07-31-fastlane-travis-weekly-deploys.md

Fix fastlane spelling

---

Dangerfile
Gemfile
Gemfile.lock

Leaves spell checking to Peril

---

_posts/2017-08-29-Making-Artsy-Editorial-Accessible.md

fixes some typos and grammar errors plus a few editorial changes.

@orta => edits for accessibility post

---

_config.yml
_posts/2017-08-30-Modernizing-Force.markdown

Post highlighting some of the steps that we've taken to modernize Force, such as the introduction of Babel, `express-reloadable` and `stitch`, as well as a hat tip to Emission and Reaction.

[Post] Modernizing Force

---

_posts/2016-08-15-React-Native-at-Artsy.markdown
_posts/2017-07-06-React-Native-for-iOS-devs.markdown
_posts/2017-08-31-Editathon.markdown

Title says it all. Will comment inline.

Use ‘reactnative’ (like other posts) and fix categories on non-tech post.

---

_posts/2017-09-05-Modernizing-Force.markdown

I guess it's possible to make an even more minor fix, but this is pretty good too. 😝

Remove duplicate word

---

_config.yml
_posts/2017-10-29-supportive-environment-for-female-engineers.markdown

Adds a note about xtina's LAA blog post

---

_posts/2017-10-10-C4Q-QandA.markdown
_posts/2017-10-29-supportive-environment-for-female-engineers.markdown

Shipped the video to our internal dropbox and youtube

Add a note about yesterday's panel

---

_posts/2017-11-27-Babel-7-and-TypeScript.markdown

[Fix] Invalid author name in post

---

_posts/2017-11-29-Express-Reloadable-Update.markdown

Fixes weird markdown link issue

[Fix] Markdown links malformed 

---

_posts/2017-12-01-engineering-blog-post-templates.markdown

Finally tracked down who proposed this idea and asked if they'd like credit :)

Adds credit for post templates idea

---

_posts/2017-07-06-React-Native-for-iOS-devs.markdown

Got some feedback from @mergesort

Adds some updates for the RN post

---

_config.yml
_posts/2017-10-10-C4Q-QandA.markdown
_posts/2018-01-10-C4Q-QandA-two.markdown

Adds a new post of the panel we ran this week.

Adds this weeks C4Q panel to the blog

---

_posts/2018-01-24-kubernetes-and-hokusai.markdown

This post details deploying the new Apogee server to our Kubernetes cluster using Hokusai. I'm sure I got some of the technical nuances wrong here, so please comment where things are incorrect or could be further clarified.

Hokusai and Kubernetes

---

Rakefile
_layouts/category_list_page.html
_layouts/series_index.html
_plugins/category_generator.rb
index.html

I mostly got this working, but it does need some design guidance, I think:
But most of the pieces are all there.

Category list page

---

_posts/2018-01-24-kubernetes-and-hokusai.markdown
_posts/2018-02-02-artsy-apogee.markdown

An initial, non-technical overview of Apogee's development before diving into a more technical post next week. WIP because I need to finish writing it.

Apogee overview

---

_layouts/series_index.html
_posts/2016-06-19-graphql-for-mobile.markdown
_posts/2016-08-15-React-Native-at-Artsy.markdown
_posts/2016-08-15-vscode.markdown
_posts/2016-08-24-On-Emission.markdown
_posts/2016-11-14-JS-Glossary.md
_posts/2017-02-05-Retrospective-Swift-at-Artsy.md

Mainly just some faffing and migrating more posts to the modern format.

Clean up the RN series

---

_posts/2018-02-06-apogee-technical-retrospective.markdown

~Just the outline so far.~
Got things wrapped up, very open to feedback.

Apogee Tech Retro

---

_posts/2017-07-06-React-Native-for-iOS-devs.markdown

re: https://twitter.com/steipete/status/964834490869800960
Thanks @steipete

Update the RN license now that it's MIT

---

.bundle/config
_config.yml
_posts/2018-03-15-integrating-redux-and-socketio.markdown

This adds a post about the technical decisions made on the article locking mechanism in positron

Integrating socket.io into react/redux app.

---

README.md

Orta and I usually follow this format to tweet out blog posts when they're published. This PR documents that process.

Documents post-publishing twitter instructions

---

_posts/2018-03-17-two-years-of-react-native.markdown

Fix Deployment typo in video timestamp link

Fix Deployment typo

---

.bundle/config
_includes/gh_comments.html
_sass/epic.scss

Displays emoji reactions from GitHub below their corresponding posts. Example: [Screenshot](https://cl.ly/2r2d1m1a3v0T)
@orta mind taking a look?

Adding comment reactions

---

_posts/2018-03-19-making-a-components-pod.markdown

Thanks to ortas help yesterday I now have a storyboards light environment I can experiment with RN Component <-> RN Host development.  
One last thing: Cmd + R is great but is this guide/blog post going to get into setting up a file watcher on App.js to automagically handle hot reloading? Or Cmd R enough of an efficiency boost?

Mention what dir to run this command in

---

_posts/2018-04-10-programmer-misconceptions-about-art.markdown
_posts/2018-04-18-programmer-misconceptions-about-art.markdown

Based on our [conversation on Slack](https://artsy.slack.com/archives/C03J4L2KK/p1523453389000765). This is a WIP because I'm sure there are more misconceptions I'm missing.

Misconceptions about Art

---

_posts/2018-04-17-making-a-components-pod.markdown

Builds on #423 which got accidentally merged.
I managed to get @daniel1of1 to give the tutorial run through, and that helped clean up another good chunk of first time run through improvements

More work on the components pod tutorial

---

_posts/2018-05-01-JavaScriptures-1-React.markdown

Adds JavaScriptures 1

---

_posts/2018-05-07-fully-automated-standups.markdown

This post documents how Orta and I automated our standup process.

Fully Automated Standups.

---

_posts/2018-05-02-JavaScriptures-2-TypeScript.markdown
_posts/2018-05-04-JavaScriptures-3-Styled-Components.markdown

Adds styled components post

---

_posts/2018-05-25-support-process.markdown

This adds a post about developing our on-call support process.

@joeyAghion => support process blog post

---

_posts/2018-06-02-Announcing-Artsy-x-React-Native.markdown
artsy-x-react-native.html

Artsy x RN announcement post

---

_posts/2018-05-30-my-first-week-on-call.markdown

This one should probably be merged first: https://github.com/artsy/artsy.github.io/pull/447

My First Week On Call

---

_config.yml
_includes/_series_bio/javascriptures.md
_includes/archive_post.html
_posts/2018-05-01-JavaScriptures-1-React.markdown
_posts/2018-05-02-JavaScriptures-2-TypeScript.markdown
_posts/2018-05-04-JavaScriptures-3-Styled-Components.markdown
_posts/2018-06-02-Announcing-Artsy-x-React-Native.markdown
_posts/2018-06-13-JavaScriptures-4.1-Relay.markdown

Creates a better series index for JavaScriptures, so we can link to it like: https://artsy.github.io/series/javascriptures/

Updates JavaScriptures infra on the blog + 4.1

---

_config.yml
_includes/_series_bio/javascriptures.md
_includes/archive_post.html
_posts/2018-05-01-JavaScriptures-1-React.markdown
_posts/2018-05-02-JavaScriptures-2-TypeScript.markdown
_posts/2018-05-04-JavaScriptures-3-Styled-Components.markdown
_posts/2018-06-02-Announcing-Artsy-x-React-Native.markdown
_posts/2018-06-13-JavaScriptures-4.1-Relay.markdown
_posts/2018-06-14-JavaScriptures-4.2-Local-State.markdown

It's set to be dated as tomorrow, but we can post whenever regardless

Adds the post for JavaScriptures 4.2 - local state

---

_config.yml
_posts/2018-06-15-JavaScriptures-5-Babel-Webpack.markdown

Same thing as #455 - but dated 2 days in advance. https://github.com/artsy/artsy.github.io/commit/ae9dcd39db3ecd21c0ed88369588f838a6da9264 is the commit that matters here.

Adds the tooling post to JS 

---

.bundle/config
_config.yml
_posts/2018-06-15-cocoapods-keys-react-native.markdown

🚧Draft 👷 ✏️ 🚧 
Soliciting feedback from new RN developers and old hats!
Don't know why .bundle/config changed!

Managing Secrets in a React Native App

---

_includes/_series_bio/react-native-at-artsy.md

Updates the RN series bio

---

_posts/2018-06-18-On-Obsessive-Statelessness.markdown

[Typo] Add missing "as"

---

_config.yml
_posts/2018-07-25-Relay-Networking-Deep-Dive.markdown

@sibelius - this is the first half of editing, I ran out of time - will pick it up again soon
A lot of my work has been to try and provide a bit more context about _why_ something is needed, or and how it comes together. Interestingly Brazilian Portuguese is my (rough) second language, so I recognize a bunch of the portuguese grammar in here 🇧🇷 
If you think this is losing your voice, I'd love you to re-edit over some of this and make it feel right for you 👍

Editing run for the Relay Network post

---

_posts/2016-01-30-iOS-Junior-Interviews.markdown

- Adds some more links, like @balestrapatrick's version of this
- Runs prettier over the page
- Switches it to the epic layout

Updates the iOS jobs blog post

---

_posts/2018-08-22-engineering-guiding-principles.markdown

I took a crack at this as requested by @orta [in Slack](https://artsy.slack.com/archives/C03J4L2KK/p1534875840000100). It's a draft, so please be ruthless in your comments about grammar, style, content, etc.
My approach was: use our experience to show how this process _can_ be done – for any team – and _then_ define our principles. They actually aren't discussed in much detail since I think the process is more important, but that's just my take.

Engineering Guiding Principles

---

blog/2018/08/10/On-Context-Switching/index.html

took a stab at what I thought you meant with that TODO. thanks for the insights!

fixes list format, removes TODO

---

_posts/2017-11-27-Babel-7-and-TypeScript.markdown

Spent half an hour trying to workout why my setup wasn’t working before I realised this invocation isn’t right 😅

Fix babel-register code example

---

_posts/2018-08-26-Dockerhub-Stamping-Commits.markdown
_posts/2018-09-10-Dockerhub-Stamping-Commits.markdown

I finally solved something that I've been working off and on forever, so it's time to write it up. Re: https://github.com/docker/hub-feedback/issues/600

Quick mini post on stamping commits via Docker Hub

---

_posts/2018-08-24-How-to-debug-jest-tests.markdown

Finally had a chance to read through this sucker so I'm just PRing some fixes. ❤️ 👍

Minor fixes for jest post

---

_posts/2018-11-21-conditional-types-in-typescript.markdown

fix typo Cirlces -> Circles

---

_config.yml
_posts/2018-10-16-switch-from-capybara-webkit-to-chrome.markdown
_posts/2018-11-27-switch-from-capybara-webkit-to-chrome.markdown

Blog post for our headless chrome migration https://github.com/artsy/volt/pull/3064! 🎉

Switch from capybara-webkit to chrome

---

_posts/2018-10-19-pair-programming.markdown

I've got feedback from friends.

Minor English correction

---

_posts/2018-12-21-why-is-swiftpm-taking-so-long.md

Fix links to buck, ninja, llbuild

---

.travis.yml
_posts/2018-12-11-GraphQL-Stitching.markdown
_posts/2019-01-03-label-based-prs.markdown

I'll give this another run through tomorrow, but most of the meat is there - anything you think is worth adding?

First draft of label-based PR deployment post

---

_posts/2019-01-05-its-time-to-use-spm.markdown

I needed to write #511 before I could write this, mainly because I though I would need to talk about the history in this post but I actually don't need to reference it at all. 
But the general pitch is: "Hey iOS folk, maybe it's time to use SPM in your projects now. Look at how it does dep man right, and your stuff is already working in that environment today."

Initial post for 'SPM is usable now'

---

_posts/2019-01-05-its-time-to-use-spm.markdown

I think it reads a little clearer like this?

Remove redundant "it's" in SPM post

---

_posts/2019-01-14-graphql-union-vs-interface.md

The introduction of the post was duplicated below the first title. Not sure the change I've made is the expected one, feel free to update it. Great blog by the way!

fix(union-vs-interface): remove duplicate content

---

README.md

Please let me know if any of this is inaccurate!

Add docs on enabling comments

---

_posts/2019-01-14-graphql-union-vs-interface.md

Sorry for this coming so late, but I ran into this blog post today and wanted to do a copy editing pass on it. As always, feel free to take or leave any or all of these suggestions!! ❤️

Some copy changes

---

_posts/2018-11-27-switch-from-capybara-webkit-to-chrome.markdown

Finally got a chance to read this one so I just wanted to give some minor copy changes that I saw while reading through. As always, feel free to take any/all of these ideas. Great post!! 🎉

Minor copy changes

---

.gitignore
_posts/2019-01-28-from-tslint-to-eslint.md

Fix caps typo

---

_posts/2019-03-12-so-you-want-to-be-an-engineer.md

I'm pretty sure this should have been a dash and the by line on the site is broken because of how the author data is defined in `_config.yml` so I took the path of least resistance and just changed this here.

Fix author name

---

_posts/2019-03-17-three-years-of-react-native.markdown

Fix a couple typos

---

_posts/2019-03-17-three-years-of-react-native.markdown

Saw an [out of context quote](https://twitter.com/lehtimaeki/status/1111543406709407745) on the tweeters.

Guard more against cherry-picking.

---

_posts/2019-04-04-peril-architecture-deep-dive.markdown
_sass/screen.scss

Just provides some background, and fixes some css on the index

Adds a post for the Peril video

---

_posts/2019-04-17-having-a-coffee-with-every-engineer.markdown
_posts/2019-04-19-having-a-coffee-with-every-engineer.markdown

Last year, I tried to meet with everyone on the engineering team for a one-on-one. I never actually finished, but the journey helped me learn about myself and my goals, as well as helped me contribute to scaling Artsy's engineering team culture.
Note: To my knowledge, this post is the first time we've publicly acknowledged _any_ difficulties scaling our culture in writing. I think it's worth it – this embodies both our Openness and People Are Paramount values. I've worked hard to strike the right tone here and I have run the post past a few Artsy engineers, but I'm always open to feedback.

What I Learned Having a Coffee with Every Engineer

---

_posts/2019-04-29-how-did-artsy-become-oss-by-default.markdown

Great post! Just a few things:
- I reworded the first sentence to be more clear.
- I changed the second sentence to not use "close" outside the "closed source" context.

Rewording a few things

---

_posts/2019-05-03-ortas-best-of.markdown

This needs to wait a while, but I got into the flow and mostly wrapped it up in one session.

Adds a "best of" post to wrap up my contributions

---

_posts/2019-05-01-technical-writing-for-teams.markdown
_posts/2019-05-06-technical-writing-for-teams.markdown

Just a draft so far, need to finish the final two sections and edit the whole thing. Getting the PR in before @orta leaves.

Writing office hours post

---

_posts/2019-05-24-server-rendering-responsively.md

Follow-up per https://github.com/artsy/artsy.github.io/pull/578#discussion_r288004347

Point post link to hash

---

_posts/2019-12-03-ios-learning-group.markdown

Here's a blog post about our recent iOS Learning Group. Rather than focus on the materials themselves, which are specific to Artsy, I chose to discuss what motivated the learning group, how the curriculum was developed+delivered, and what we learned for next time. 
Open to any and all feedback, especially if anyone has a better idea for a title.

iOS Learning Group

---

_posts/2020-01-03-graphql-custom-directives.markdown
_posts/2020-01-13-graphql-custom-directives.markdown

and specifically how we use them to help tighten up our error handling.
~This is still a WIP, mostly because I need to add in a bunch of links (placeholders for now).~

[Custom Directive] Add post about GraphQL custom directives

---

_posts/2020-01-15-ios-logout-button-at-last.markdown

Adds `a`, changing the sentence `We run these events roughly once year` to `We run these events roughly once a year`.

[Grammar] Changes sentence

---

_posts/2020-02-20-deploying-canaries-with-auto.markdown

Typo correction

---

_posts/2020-02-20-deploying-canaries-with-auto.markdown

Great post @zephraph — just some minor copyedits here (and some bot copyedits as well I guess)

Minor copyedits to canary post

---

_config.yml
_posts/2020-07-15-from-engineering-to-product-management-and-back-again.md

This blog post goes over my journey from transitioning from engineering to product management and then coming back to engineering. It details how PMing is different from engineering, what I learned and how my experience as an engineer is different now.

From engineering to product management, and back again

---

_config.yml
podcast.xml

Adds the first episode to the podcast feed!
Includes small modifications to the podcast.xml template to make it work with this episode's data.

feat: episode 1 of Artsy Engineering Radio

---

_config.yml

Featuring myself, @mdole, and @jonallured. 
This episode is a short discussion about why we we're starting a podcast.
I moved this episode above episode 1 in the config, I don't know how or if that will affect anyone that was already pointed at this feed (which is probably no one). 
Assigned to myself: I'll wait for feedback on the title & description before I merge.

feat: podcast episode 0 - introducing Artsy Engineering Radio

---

_config.yml

Brought up in Slack: https://artsy.slack.com/archives/C6CLYE5C7/p1608593194021400
/cc @pepopowitz @dblandin

chore: make episode 0 the first episode

---

_posts/2020-12-31-echo-supporting-old-app-versions.markdown

This fixes a typo that @pepopowitz pointed out, and also adds a link to Pavlos' GitHub page. @pvinis feel free to change this, or remove it, prior to merging 👍 Whatever you prefer.

feedback: apply feedback from #642

---

_config.yml

Lesson 1 in introducing yourself: spell introducing correctly. 😬

fix: spelling error in podcast episode 0's title

---

_posts/2021-01-06-introducing-artsy-engineering-radio.markdown

collab with @jonallured 
Hey, we have some podcast episodes! Let's announce it.
I'm not sure if we want to add a comment thread for this -- I could see it being useful for people to let us know it's not in their preferred podcast player, but not much beyond that.
Right now the episodes link to itunes because that's the only place they exist. I'm going to reach out to Google today to see why it's not there yet, and publish to Spotify & Stitcher today.

feat: Introducing Artsy Engineering Radio post

---

_posts/2020-12-09-share-your-knowledge.markdown

Just happened to catch this while reading — let me know if anything needs to be changed!

chore: update link to previous post

---

_config.yml
_posts/2021-02-11-asking-for-help.markdown

I added my story from Medium onto the blog and added myself as an author.
Question: The below looks a little weird like there's an extra line? Or maybe that's how it's supposed to look?

Add myself (as an author) and post asking for help story to blog

---

googlef51b779dd18cf8a4.html

Over on #668 I added the verification file to the `master` branch rather than the `source` branch and that doesn't work so I _think_ this is what I wanted to do. 😕

Correctly add verification file

---

_config.yml

fix: episode number

---

_config.yml

It's here! Editing 40 minute episodes takes a hot minute as it turns out.
Give it a skim and let me know what you think! Too loud? Too soft? Are some people louder than others? What did I miss?

feat: Episode 12: Request for Comment #1

---

_posts/2021-04-14-accessing-the-relay-store.markdown
_posts/2021-04-15-accessing-the-relay-store.markdown

From our convo yesterday about `commitLocalUpdate`. Definitely needs another read and maybe editing out of some of the non-Relay parts of the tale. But would love to know if I missed any of the technical details, particularly @damassi what you and I had discussed about your previous understanding of `commitLocalUpdate`. Maybe it makes sense to include that here?

Add post about accessing the relay store via commitLocalUpdate

---

_posts/2021-04-15-testing-react-tracking-with-jest-and-enzyme.markdown

Open to any feedback on this! Worried it might go into a bit too much detail/not be understood by someone who hasn't worked on this code or with these tools before. Will return to it tomorrow after sleeping on it.

feat: post on testing react-tracking with jest and enzyme

---

_posts/2021-04-15-testing-react-tracking-with-jest-and-enzyme.markdown

- Correct comment id
- Simplify tracking call (I thought I did this previously but my push was rejected due to a conflicting commit oops)
- Add a bit more context to the mocked tracking call

chore: fix a few things I missed

---

_posts/2021-04-15-accessing-the-relay-store.markdown

I forgot to enable commenting on my article so adding that here!

fix: Add commenting to relay store post

---

_config.yml

Intended to publish Thursday, April 22. 
Featuring @jonallured, @pvinis, and @dblandin! Give it a listen & let me know what you think. 
Also, I pretended I was a musician and made a song for you after the credits.

feat: episode 14, request for comment 2

---

_config.yml

New podcast ep!!! Let me know how the sound sounds? As always open to any and all feedback. (The second half is a bit shorter, closer to 25 mins I think.)

feat: Add podcast episode with dB

---

_config.yml

Really enjoyed this one, great work Damon & Tricia!

feat: episode 18, Tricia & Damon talk accessibility

---

_config.yml

cc @ds300 
Feel free to leave feedback, otherwise I'll plan to ship this later today!!!

feat: episode 21 - David & how we broke down the android project into something not terrifyingly large

---

_config.yml

This PR adds episode 22 to our feed which I am now realizing isn't technically required any longer for publishing an episode! Either way, going to PR this and go from there.

Add metadata for Episode 22

---

_posts/2021-09-07-what-javascript-tests-could-learn-from-rspec.md

I started writing this article for my personal site, but @annacarey encouraged me to put it on the Artsy engineering blog, too. It's kind of opinion-y and complain-y, and if you think that's not appropriate, say so!
Also, if I'm completely off-base with my let/context rspec examples, let me know!
My intention after I gather any feedback is to ship to my site first, then add a `rel=canonical` link pointing back to it from here.

feat: article on rspec/jest

---

README.md

This PR adds some helpful suggestions to the setup docs, for an issue I and @laurabeth have both run into with dependency installation.
I don't know enough about the dependencies to know which exact commands work in which scenarios, but I had these in my personal notes and it seems appropriate to share them.

docs: add helpful commands for resolving therubyracer/v8 dependency installation issues

---

.travis.yml
Rakefile

Favor inclusive language in the codebase per this [RFC](https://github.com/artsy/README/issues/427).
---
Includes updates to the build/deploy tasks, now that this repo uses a `main` branch.

feat: adopt inclusive language - rename master to main

---

_config.yml
_posts/2022-02-01-using-context-to-simplify-a-react-form.md

Anna and I talk about our impressions and processes leading up to/during refactoring the artwork form in volt.
co-authored by: @annacarey and @pepopowitz

add form context blog post co-authored by anna

---

_posts/2022-04-13-stepping-out-of-the-knowledge-zone.md

@kajatiger noticed your recent post didn't have a `` tag, so the whole thing was rendering on the homepage :) adding one in!
<details><summary>Before:</summary>
</details>
<details><summary>After:</summary>
/>
</details>

chore: add 'more' tag to recent post

---

_posts/2022-08-23-getting-around-7-day-cookie.markdown

- Little things here and there to (subjectively) improve readability
- Extracted the inline links in favor of reference links

chore: minor updates to 7-day cookie limit post

---

_posts/2022-08-23-getting-around-7-day-cookie.markdown
_posts/2022-09-07-quick-tips-to-speed-up-ci.markdown

New post on how we recently added jest sharding and parallization for Cypress.io, which reduced our test runner times by over half. 
Proof-readers welcome 🙏 🙏 
cc @artsy/grow-devs

feat: Add post on Parallelizing Jest and Cypress.io Tests on CircleCI

---

_posts/2022-09-07-quick-tips-to-speed-up-ci.markdown

Fixes a few (buggy) markdown link aliases.

Fix some links

---

_posts/2022-09-07-quick-tips-to-speed-up-ci.markdown

Fix one more link

---

.env.example
.gitignore
Gemfile
Gemfile.lock
README.md
Rakefile
_includes/head.html
_layouts/default.html
_layouts/epic.html
css/epic.scss
javascripts/related-articles.js
lib/article_iterator.rb
lib/related_articles.rb
lib/related_articles/database.rb
related-articles.json

This PR adds the ability to include a short list of related articles at the bottom of each article on the blog.
For example the article at [Accessing the Relay Store Without a Mutation](https://artsy.github.io/blog/2021/04/15/accessing-the-relay-store/) might include a block such as the following:
> **You might also like**
> - [Relay Mutations](https://artsy.github.io/blog/2017/04/26/Relay-Mutations)
> - [Why does Artsy use Relay?](https://artsy.github.io/blog/2019/04/10/omakase-relay)
> - [Relay Pagination Containers Demystified](https://artsy.github.io/blog/2020/08/31/relay-pagination-containers-demystified)
(Real example from the current batch^)
The goal here was to find a simple + low-stakes use case to start experimenting with:
- Our brand new [Weaviate](https://weaviate.io) cluster, …

feat: add "similar articles" functionality #FF

---

_posts/2023-09-13-deploying-a-scary-change.md

Lil post on deploying changes to production safely

feat: new post on deploying a scary change

---

_posts/2023-09-13-deploying-a-scary-change.md

spaced doing this right away. Followup to #753

chore: add comment thread to scary change post

---

_posts/2023-03-07-nextjs-at-artsy-retrospective.markdown

Covers the last two years of Next.js at Artsy! And some of our concerns. 
Needs some editing and Feedback 🙏

feat(post): Two years of Next.js at Artsy: A Retrospective

---

_posts/2023-03-07-nextjs-at-artsy-retrospective.markdown
_posts/2024-03-07-nextjs-at-artsy-retrospective.markdown

fix: next post typos 

---

_posts/2024-03-07-nextjs-at-artsy-retrospective.markdown

fix: Fixes some typos in the Next post
